src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="text")
     */
    private $img;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text")
     */
    private $link;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }
}

src/Entity/Projects.php
<?php

namespace App\Entity;


use App\Repository\ProjectsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ProjectsRepository::class)
 * @Vich\Uploadable
 */
class Projects
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $img;

    /**
     * @Vich\UploadableField(mapping="imageproject", fileNameProperty="img")
     * @var File
     */

    public $imageFile;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="array")
     * @var string[]
     */
    private $technos = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $urlType;

    /**
     * @ORM\OneToMany(targetEntity=Commentaries::class, mappedBy="project", orphanRemoval=true)
     */
    private $commentaries;

    public function __construct()
    {
        $this->commentaries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg( $img): self
    {
        $this->img = $img;

        return $this;
    }

    /**
     * @return File/null
     */
    public function getImgFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File/null $imgFile
     */
    public function setImgFile(?File $imageFile = null)
    {
        $this->imageFile = $imageFile;

    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTechnos(): ?array
    {
        return $this->technos;
    }

    public function setTechnos(array $technos): self
    {
        $this->technos = $technos;

        return $this;
    }

    public function getUrlType(): ?string
    {
        return $this->urlType;
    }

    public function setUrlType(?string $urlType): self
    {
        $this->urlType = $urlType;

        return $this;
    }

    /**
     * @return Collection<int, Commentaries>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentaries $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries[] = $commentary;
            $commentary->setProject($this);
        }

        return $this;
    }

    public function removeCommentary(Commentaries $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getProject() === $this) {
                $commentary->setProject(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $surname;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $grade;

    /**
     * @ORM\Column(type="text")
     */
    private $git;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_asso;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $logo;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getGrade(): ?int
    {
        return $this->grade;
    }

    public function setGrade(?int $grade): self
    {
        $this->grade = $grade;

        return $this;
    }

    public function getGit(): ?string
    {
        return $this->git;
    }

    public function setGit(string $git): self
    {
        $this->git = $git;

        return $this;
    }

    public function getIsAsso(): ?bool
    {
        return $this->is_asso;
    }

    public function setIsAsso(bool $is_asso): self
    {
        $this->is_asso = $is_asso;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

}

src/Controller/ProjectsController.php
<?php

namespace App\Controller;

use App\Entity\Projects;
use App\Entity\Commentaries;
use App\Form\CommentFormType;
use App\Repository\ProjectsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry as PersistenceManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProjectsController extends AbstractController
{
    /** @var ProjectsRepository */
    private $projectsRepository;

    public function __construct(EntityManagerInterface $objectManager)
    {
        $this->projectsRepository = $objectManager->getRepository(Projects::class);
    }

    #[Route('/projects', name: 'projects')]
    public function index(): Response
    {
        $project = $this->projectsRepository->findAll();
        return $this->render('projects/index.html.twig', [
            'projects' => $project,
        ]);
    }

    #[Route('/projects/{id}', name: 'projects_show')]
    public function show(ProjectsRepository $projectsRepository, $id, Request $request, EntityManagerInterface $manager): Response
    {
        $project = $projectsRepository->find($id);


        // Commentaire Section
        
        $comment = new Commentaries();

        // gestion du commentaire
        $commentForm = $this->createForm(CommentFormType::class, $comment);

        $commentForm->handleRequest($request);

        // traitement du formulaire 
        if($commentForm->isSubmitted() && $commentForm->isValid()){

            //on add l'id de l'annonce 
            $comment->setProject($project);

            // récuperation du parentid 
            $parentid = $commentForm->get('parentid')->getData();

            // on va chercher le com correspondant au parentid
            if($parentid != null){
                $parent = $manager->getRepository(Commentaries::class)->find($parentid);

                 // on défini le parent du commentaire
                $comment->setParent($parent ?? null);
            }

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash('success', 'Votre commentaire a bien été ajouté');
            return $this->redirectToRoute('projects_show', ['id' => $id]);
            
        }


        return $this->render('projects/show.html.twig', [
            'project' => $project,
            'commentForm' => $commentForm->createView()
        ]);
    }   
    
}

templates/projects/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

	<div>

		<h1>Welcome to Projects</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec finibus nunc. Aenean tristique blandit urna vel accumsan. Fusce id ante nec magna lacinia placerat. Ut ornare metus eget elementum aliquet. Aliquam maximus elit ac ex iaculis, non ullamcorper augue suscipit. Aliquam ornare velit est, eget ultricies ligula tempor pretium. Quisque fermentum malesuada odio sed cursus. Quisque ultrices facilisis lectus, tristique elementum nunc aliquet vitae. Proin feugiat dignissim erat, eu iaculis urna rhoncus eget. Nam vel justo eget augue pharetra pharetra ac quis eros. Vestibulum facilisis ipsum est. Vestibulum libero turpis, lobortis eu porttitor fringilla, elementum vitae ex. Suspendisse potenti. Nam tincidunt purus a mauris cursus, sit amet feugiat ex tincidunt. Pellentesque aliquet luctus fermentum.</p>
	</div>

	<div>

		{% for project in projects %}

			<div>
				<div>
					<h2>{{ project.title }}</h2>
					<img src="{{ vich_uploader_asset(project, 'imageFile') }}" alt="projectpic">
					<p>{{ project.description }}</p>
					{% for techno in project.technos %}
					<p>{{ techno }}</p>
					{% endfor %}
                    <span><a href=" {{ path('projects_show', {'id' : project.id}) }} ">More information</a></span>
				</div>

			</div>
		{% endfor %}
	</div>


{% endblock %}

templates/projects/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!{% endblock %}

{% block body %}

<!-- ======= Whu Us Section ======= -->
    <section id="why-us" class="why-us">
        <div class="container">

            <div class="section-title">
                
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="box">
                        <h4>{{ project.title }}</h4>
                        <img src="{{ vich_uploader_asset(project, 'imageFile') }}" alt="projectpic">
                        <p>{{ project.description }}</p>
                    </div>
                </div>
            </div>

            <div class="FormContent">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}

                {% for message in app.flashes('error') %}
                    <div class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endfor %}

                <div class="Commentaire--Liste">
                    <h2>Liste des Commentaires</h2>
                    <ul>
                        {% for comment in project.commentaries %}
                            {% if comment.parent == null %} 
                                <div class="Commentaire--Contenu">
                                    <div class="Commentaire--Contenu--Auteur">
                                        <h3>Publié par {{ comment.username }}</h3>
                                        <p>{{ comment.createdAt|date('d/m/Y') }}</p>
                                    </div>
                                    <div class="Commentaire--Contenu--Contenu">
                                        <p>{{ comment.comment }}</p>
                                        <span><a href="#ajout-commentaire" data-reply data-id="{{ comment.id }}"  >Répondre au commentaire</a></span>
                                    </div>
                                </div>
                                {# Afficher les reponces  #}
                                {% for reply in comment.replies %}
                                    <div class="Commentaire--Contenu">
                                        <div class="Commentaire--Contenu--Auteur">
                                            <h3>Publié par {{ reply.username }}</h3>
                                            <p>{{ reply.createdAt|date('d/m/Y') }}</p>
                                        </div>
                                        <div class="Commentaire--Contenu--Contenu">
                                            <p>{{ reply.comment }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}

                        {% endfor %}
                    </ul>
                </div>
                <div class="Commentaire--add" id="ajout-commentaire" >
                    <h2>Ajouter un Commentaire</h2>
                    {{ form(commentForm) }}
                </div>
            </div>
        </div>
    </section><!-- End Whu Us Section -->


    <script src="/js/commentaire.js"></script>


{% endblock %}